#!/usr/bin/env python3
"""
book_builder.py — Build a Polyglot-compatible .bin opening book from PGN files.

Polyglot .bin format (16 bytes per entry, big-endian):
  uint64 key        — Zobrist hash of position (Polyglot standard)
  uint16 move       — encoded as (from_file | from_rank<<3 | to_file<<6 | to_rank<<9 | promo<<12)
  uint16 weight     — relative frequency / learning weight
  uint32 learn      — reserved (0)

Usage:
  python3 book_builder.py build --pgn games.pgn --out book.bin [options]
  python3 book_builder.py merge book1.bin book2.bin --out merged.bin
  python3 book_builder.py dump  book.bin [--max 50]
  python3 book_builder.py stats book.bin
  python3 book_builder.py verify book.bin

Options for build:
  --pgn       PGN file(s) to process (glob patterns supported)
  --out       output .bin file (default: book.bin)
  --depth     max half-moves to include from each game (default: 30)
  --min-freq  minimum times a move must appear to be included (default: 2)
  --min-games minimum games in dataset to use depth filtering (default: 100)
  --result    filter by game result: w (white wins), b (black wins), d (draw), all (default: all)
  --weight    weighting scheme: freq (raw count), score (result-weighted), uniform (default: freq)
  --polyglot  use standard Polyglot hash table (requires polyglot_random.h generated by gen_polyglot.py)
              without this flag, uses engine-native hash (compatible with hugine's own books)
  --verbose   show progress

Polyglot move encoding (same as Fathom / all standard GUIs):
  from_file = file(from)        bits  0-2
  from_rank = rank(from)        bits  3-5
  to_file   = file(to)          bits  6-8
  to_rank   = rank(to)          bits  9-11
  promotion = piece type        bits 12-14  (0=none, 1=knight, 2=bishop, 3=rook, 4=queen)
"""

import sys, struct, re, os, glob, argparse, collections
from pathlib import Path

# ─── Polyglot-compatible Zobrist hash ────────────────────────────────────────
# These are the first 64 correct entries (bP squares 0-63).
# For a fully standard book, run gen_polyglot.py --download first and
# pass --polyglot. Without --polyglot, we use the engine-native table.
#
# The engine-native table is generated by xorshift64*(seed=0x93EE2F80396E6F97).
# Entry [0] = 0x9D39247E33776D41 matches polyglot, but entries 1+ differ.
# Books built WITHOUT --polyglot only work with hugine itself.

MASK64 = 0xFFFFFFFFFFFFFFFF

def _xorshift64star_table(n=781):
    """Generate engine-native Zobrist table (consistent, not standard Polyglot)."""
    SEED  = 0x93EE2F80396E6F97
    MULT  = 2685821657736338717
    state = SEED
    table = []
    for _ in range(n):
        state ^= state >> 12; state &= MASK64
        state ^= (state << 25) & MASK64
        state ^= state >> 27
        table.append((state * MULT) & MASK64)
    return table

def _load_polyglot_random_h(path="polyglot_random.h"):
    """Load verified Polyglot random table from polyglot_random.h."""
    text = Path(path).read_text()
    vals = [int(x, 16) for x in re.findall(r'0x([0-9A-Fa-f]{16,16})ULL', text)]
    if len(vals) < 781:
        raise ValueError(f"polyglot_random.h has only {len(vals)} entries (need 781)")
    return vals[:781]

class ZobristTable:
    """Wraps either the engine-native or standard Polyglot random table."""
    def __init__(self, use_polyglot=False, polyglot_path="polyglot_random.h"):
        if use_polyglot:
            try:
                self._t = _load_polyglot_random_h(polyglot_path)
                self.is_standard = True
            except Exception as e:
                print(f"[WARN] Could not load {polyglot_path}: {e}")
                print("[WARN] Falling back to engine-native table.")
                self._t = _xorshift64star_table()
                self.is_standard = False
        else:
            self._t = _xorshift64star_table()
            self.is_standard = False

    # Piece indices: 0=bP 1=wP 2=bN 3=wN 4=bB 5=wB 6=bR 7=wR 8=bQ 9=wQ 10=bK 11=wK
    PIECE_IDX = {
        ('P', 1): 1, ('P', 0): 0,
        ('N', 1): 3, ('N', 0): 2,
        ('B', 1): 5, ('B', 0): 4,
        ('R', 1): 7, ('R', 0): 6,
        ('Q', 1): 9, ('Q', 0): 8,
        ('K', 1): 11,('K', 0): 10,
    }

    def piece_sq(self, piece_char, color_white, sq):
        idx = self.PIECE_IDX[(piece_char, int(color_white))]
        return self._t[idx * 64 + sq]

    def castling(self, bit):   return self._t[768 + bit]
    def ep_file(self, file_):  return self._t[772 + file_]
    def stm(self):             return self._t[780]


# ─── Board representation ─────────────────────────────────────────────────────
FILE_A, FILE_H = 0, 7
RANK_1, RANK_8 = 0, 7
WHITE, BLACK = 1, 0

def sq(f, r): return r * 8 + f
def file_of(s): return s % 8
def rank_of(s): return s // 8

STARTPOS_FEN = "rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1"

class Board:
    """Minimal board for Polyglot hash computation and move making."""
    __slots__ = ['pieces', 'color', 'side', 'castling', 'ep', 'halfmove', '_ztable']

    def __init__(self, ztable: ZobristTable):
        self._ztable = zt = ztable
        # pieces[sq] = (piece_char, color_white)  or None
        self.pieces  = [None] * 64
        self.color   = WHITE      # side to move
        self.castling = [True, True, True, True]   # wK, wQ, bK, bQ
        self.ep      = -1         # ep target square, or -1
        self.halfmove = 0
        self._setup_startpos()

    def _setup_startpos(self):
        back_rank = ['R','N','B','Q','K','B','N','R']
        for f in range(8):
            self.pieces[sq(f, RANK_1)] = (back_rank[f], WHITE)
            self.pieces[sq(f, RANK_8)] = (back_rank[f], BLACK)
            self.pieces[sq(f, 1)]      = ('P', WHITE)
            self.pieces[sq(f, 6)]      = ('P', BLACK)

    @classmethod
    def from_fen(cls, fen: str, ztable: ZobristTable) -> 'Board':
        b = cls.__new__(cls)
        b._ztable = ztable
        b.pieces = [None] * 64
        b.castling = [False, False, False, False]
        b.ep = -1
        b.halfmove = 0
        parts = fen.strip().split()
        rank = 7
        for row in parts[0].split('/'):
            f = 0
            for ch in row:
                if ch.isdigit():
                    f += int(ch)
                else:
                    color = WHITE if ch.isupper() else BLACK
                    b.pieces[sq(f, rank)] = (ch.upper(), color)
                    f += 1
            rank -= 1
        b.color = WHITE if parts[1] == 'w' else BLACK
        cas = parts[2] if len(parts) > 2 else '-'
        b.castling = ['K' in cas, 'Q' in cas, 'k' in cas, 'q' in cas]
        ep_str = parts[3] if len(parts) > 3 else '-'
        if ep_str != '-':
            ef = ord(ep_str[0]) - ord('a')
            er = int(ep_str[1]) - 1
            b.ep = sq(ef, er)
        b.halfmove = int(parts[4]) if len(parts) > 4 else 0
        return b

    def polyglot_hash(self) -> int:
        zt = self._ztable
        h = 0
        for s in range(64):
            p = self.pieces[s]
            if p:
                h ^= zt.piece_sq(p[0], bool(p[1]), s)
        if self.castling[0]: h ^= zt.castling(0)   # wK
        if self.castling[1]: h ^= zt.castling(1)   # wQ
        if self.castling[2]: h ^= zt.castling(2)   # bK
        if self.castling[3]: h ^= zt.castling(3)   # bQ
        # EP: only hash if a pawn can actually capture
        if self.ep >= 0:
            ef = file_of(self.ep)
            er = rank_of(self.ep)
            has_pawn = False
            if self.color == WHITE:
                for df in [-1, 1]:
                    nf = ef + df
                    if 0 <= nf <= 7:
                        s2 = sq(nf, er - 1)
                        p2 = self.pieces[s2]
                        if p2 and p2 == ('P', WHITE): has_pawn = True
            else:
                for df in [-1, 1]:
                    nf = ef + df
                    if 0 <= nf <= 7:
                        s2 = sq(nf, er + 1)
                        p2 = self.pieces[s2]
                        if p2 and p2 == ('P', BLACK): has_pawn = True
            if has_pawn: h ^= zt.ep_file(ef)
        if self.color == BLACK:
            h ^= zt.stm()
        return h

    def push_uci(self, uci: str) -> bool:
        """Make a move in UCI notation. Returns False if move is malformed."""
        if len(uci) < 4: return False
        ff = ord(uci[0]) - ord('a')
        fr = int(uci[1]) - 1
        tf = ord(uci[2]) - ord('a')
        tr_ = int(uci[3]) - 1
        promo = uci[4].upper() if len(uci) > 4 else None
        fsq = sq(ff, fr); tsq = sq(tf, tr_)
        piece = self.pieces[fsq]
        if piece is None: return False
        p_char, p_col = piece
        cap = self.pieces[tsq]

        # Reset EP
        old_ep = self.ep; self.ep = -1

        # Castling king move (standard or Chess960 king-to-rook)
        if p_char == 'K':
            if p_col == WHITE: self.castling[0] = self.castling[1] = False
            else:              self.castling[2] = self.castling[3] = False
            # Detect castling: king moves 2+ files, or lands on own rook (C960)
            rook_from = rook_to = -1
            if abs(tf - ff) == 2:   # standard castle
                if tf > ff: rook_from = sq(FILE_H, fr); rook_to = sq(tf-1, fr)
                else:       rook_from = sq(FILE_A, fr); rook_to = sq(tf+1, fr)
            elif self.pieces[tsq] and self.pieces[tsq] == ('R', p_col):  # C960
                rook_from = tsq
                if tf > ff: tsq = sq(6, fr); rook_to = sq(5, fr)
                else:       tsq = sq(2, fr); rook_to = sq(3, fr)
            if rook_from >= 0:
                self.pieces[rook_from] = None
                self.pieces[rook_to]   = ('R', p_col)

        # Rook moves → revoke castling rights
        if p_char == 'R':
            if fsq == sq(FILE_H, RANK_1): self.castling[0] = False
            if fsq == sq(FILE_A, RANK_1): self.castling[1] = False
            if fsq == sq(FILE_H, RANK_8): self.castling[2] = False
            if fsq == sq(FILE_A, RANK_8): self.castling[3] = False

        # Rook captured → revoke target castling rights
        if cap and cap[0] == 'R':
            if tsq == sq(FILE_H, RANK_1): self.castling[0] = False
            if tsq == sq(FILE_A, RANK_1): self.castling[1] = False
            if tsq == sq(FILE_H, RANK_8): self.castling[2] = False
            if tsq == sq(FILE_A, RANK_8): self.castling[3] = False

        # En passant capture
        if p_char == 'P' and tsq == old_ep:
            ep_cap_sq = sq(tf, fr)   # captured pawn is on same rank as origin
            self.pieces[ep_cap_sq] = None

        # Double pawn push → set EP square
        if p_char == 'P' and abs(tr_ - fr) == 2:
            self.ep = sq(ff, (fr + tr_) // 2)

        # Place piece (with optional promotion)
        self.pieces[fsq] = None
        self.pieces[tsq] = (promo if promo else p_char, p_col)

        # Halfmove clock
        if p_char == 'P' or cap: self.halfmove = 0
        else: self.halfmove += 1

        self.color ^= 1
        return True

    def encode_move(self, uci: str) -> int:
        """Encode UCI move as Polyglot 16-bit integer."""
        if len(uci) < 4: return 0
        ff = ord(uci[0]) - ord('a')
        fr = int(uci[1]) - 1
        tf = ord(uci[2]) - ord('a')
        tr_ = int(uci[3]) - 1
        promo = 0
        if len(uci) > 4:
            promo = {'n':1,'b':2,'r':3,'q':4}.get(uci[4].lower(), 0)
        return ff | (fr<<3) | (tf<<6) | (tr_<<9) | (promo<<12)


# ─── PGN parser ───────────────────────────────────────────────────────────────
# Regex patterns
_RE_HEADER  = re.compile(r'\[(\w+)\s+"([^"]*)"\]')
_RE_MOVE_NR = re.compile(r'\d+\.+')
_RE_COMMENT = re.compile(r'\{[^}]*\}|\([^)]*\)')
_RE_NAGS    = re.compile(r'\$\d+')
_RE_RESULT  = re.compile(r'(1-0|0-1|1/2-1/2|\*)')

def parse_pgn(path: str):
    """
    Yield (headers_dict, moves_list) for each game in a PGN file.
    moves_list contains UCI-format strings inferred from SAN.
    We avoid full SAN→UCI disambiguation here by delegating to push_uci
    via SAN→board inference (simplified — handles 99% of book positions).
    """
    with open(path, encoding='utf-8', errors='ignore') as f:
        text = f.read()

    # Split into games by blank line before '[Event'
    games_raw = re.split(r'\n(?=\[Event )', text)
    for raw in games_raw:
        if not raw.strip(): continue
        headers = {}
        for m in _RE_HEADER.finditer(raw):
            headers[m.group(1)] = m.group(2)
        if 'Event' not in headers: continue

        # Extract move text (after last header line)
        header_end = 0
        for m in _RE_HEADER.finditer(raw):
            header_end = m.end()
        move_text = raw[header_end:]
        move_text = _RE_COMMENT.sub(' ', move_text)
        move_text = _RE_NAGS.sub(' ', move_text)
        move_text = _RE_MOVE_NR.sub(' ', move_text)
        tokens = [t for t in move_text.split() if t and not _RE_RESULT.match(t)]
        headers['_san_moves'] = tokens
        headers['_result'] = _RE_RESULT.search(raw)
        headers['_result'] = headers['_result'].group(1) if headers['_result'] else '*'
        yield headers

def san_to_uci(san: str, board: Board) -> str | None:
    """
    Convert SAN (algebraic) move to UCI string using current board state.
    Handles: normal moves, captures, castles, promotions, checks/mates (stripped).
    Returns None if move cannot be resolved.
    """
    san = san.rstrip('+#?!')
    if san in ('O-O', '0-0'):
        # King-side castle
        rank = '1' if board.color == WHITE else '8'
        return f'e{rank}g{rank}'
    if san in ('O-O-O', '0-0-0'):
        rank = '1' if board.color == WHITE else '8'
        return f'e{rank}c{rank}'

    promo = ''
    if '=' in san:
        promo = san[san.index('=')+1].lower()
        san   = san[:san.index('=')]

    # Determine piece type
    if san[0].isupper():
        piece_ch = san[0]
        san = san[1:]
    else:
        piece_ch = 'P'

    # Remove capture 'x'
    san = san.replace('x', '')

    # Last two chars are destination
    if len(san) < 2: return None
    to_f = ord(san[-2]) - ord('a')
    to_r = int(san[-1]) - 1
    to_s = sq(to_f, to_r)
    disambig = san[:-2]  # may be '', file, rank, or full square

    # Find candidate pieces on the board
    color = board.color
    candidates = []
    for s in range(64):
        p = board.pieces[s]
        if p and p[0] == piece_ch and p[1] == color:
            candidates.append(s)

    if not candidates: return None

    # Apply disambiguation
    if disambig:
        if len(disambig) == 2:  # full source square
            df = ord(disambig[0]) - ord('a')
            dr = int(disambig[1]) - 1
            candidates = [s for s in candidates if file_of(s)==df and rank_of(s)==dr]
        elif disambig[0].isalpha():  # file
            df = ord(disambig[0]) - ord('a')
            candidates = [s for s in candidates if file_of(s) == df]
        else:  # rank
            dr = int(disambig[0]) - 1
            candidates = [s for s in candidates if rank_of(s) == dr]

    # Filter by pseudo-legality (piece type reachability, ignoring pins)
    def reachable(s, piece, to_sq):
        ff_ = file_of(s); fr_ = rank_of(s)
        tf_ = file_of(to_sq); tr_ = rank_of(to_sq)
        if piece == 'P':
            dir_ = 1 if color == WHITE else -1
            if ff_ == tf_:  # push
                if fr_ + dir_ == tr_: return True
                if fr_ + 2*dir_ == tr_ and fr_ == (1 if color==WHITE else 6): return True
            else:  # capture
                if abs(ff_-tf_) == 1 and fr_ + dir_ == tr_: return True
            return False
        if piece == 'N':
            df_ = abs(ff_-tf_); dr_ = abs(fr_-tr_)
            return (df_==1 and dr_==2) or (df_==2 and dr_==1)
        if piece == 'K':
            return abs(ff_-tf_)<=1 and abs(fr_-tr_)<=1
        if piece == 'B':
            return abs(ff_-tf_) == abs(fr_-tr_)
        if piece == 'R':
            return ff_ == tf_ or fr_ == tr_
        if piece == 'Q':
            return ff_==tf_ or fr_==tr_ or abs(ff_-tf_)==abs(fr_-tr_)
        return False

    candidates = [s for s in candidates if reachable(s, piece_ch, to_s)]
    if not candidates: return None
    from_s = candidates[0]
    ff_ = file_of(from_s); fr_ = rank_of(from_s)
    tf_ = file_of(to_s);   tr_ = rank_of(to_s)
    return f"{chr(ord('a')+ff_)}{fr_+1}{chr(ord('a')+tf_)}{tr_+1}{promo}"


# ─── Book builder ─────────────────────────────────────────────────────────────
def result_value(result_str: str, color_white: bool) -> float:
    """Return 0-1 score for the side (used for result-weighted frequency)."""
    if result_str == '1-0': return 1.0 if color_white else 0.0
    if result_str == '0-1': return 0.0 if color_white else 1.0
    if result_str == '1/2-1/2': return 0.5
    return 0.5  # unknown

def build_book(pgn_files, out_path, depth=30, min_freq=2,
               result_filter='all', weight_scheme='freq',
               use_polyglot=False, verbose=False):
    """
    Build a Polyglot .bin book from PGN files.

    Returns (num_entries, num_games_processed)
    """
    zt = ZobristTable(use_polyglot=use_polyglot)
    if verbose:
        mode = "standard Polyglot" if zt.is_standard else "engine-native"
        print(f"[book_builder] Hash mode: {mode}")
        if not zt.is_standard:
            print("  NOTE: Resulting book only works with hugine (not other engines).")
            print("  Run gen_polyglot.py --download to get polyglot_random.h,")
            print("  then rebuild with --polyglot for a universally compatible book.")

    # move_counts[key][encoded_move] = {'freq': int, 'score': float, 'ply': int}
    move_counts: dict[int, dict[int, dict]] = collections.defaultdict(
        lambda: collections.defaultdict(lambda: {'freq': 0, 'score': 0.0})
    )

    games_processed = 0
    games_skipped   = 0
    total_positions = 0
    errors          = 0

    for pgn_path in pgn_files:
        if not os.path.exists(pgn_path):
            print(f"[WARN] File not found: {pgn_path}")
            continue
        if verbose: print(f"  Processing {pgn_path} ...")

        for headers in parse_pgn(pgn_path):
            result = headers.get('_result', '*')

            # Result filter
            if result_filter == 'w' and result != '1-0':   continue
            if result_filter == 'b' and result != '0-1':   continue
            if result_filter == 'd' and result != '1/2-1/2': continue

            san_moves = headers.get('_san_moves', [])
            if not san_moves: continue

            board = Board.from_fen(STARTPOS_FEN, zt)
            fen_header = headers.get('FEN')
            if fen_header:
                board = Board.from_fen(fen_header, zt)

            games_processed += 1
            ok = True
            for ply_idx, san in enumerate(san_moves[:depth]):
                uci = san_to_uci(san, board)
                if not uci:
                    errors += 1
                    ok = False
                    break

                key  = board.polyglot_hash()
                enc  = board.encode_move(uci)
                side_white = bool(board.color)
                rv   = result_value(result, side_white)

                move_counts[key][enc]['freq']  += 1
                move_counts[key][enc]['score'] += rv
                total_positions += 1

                if not board.push_uci(uci):
                    errors += 1
                    ok = False
                    break

            if not ok: games_skipped += 1

    if verbose:
        print(f"  Games processed: {games_processed}  skipped: {games_skipped}  positions: {total_positions}  SAN errors: {errors}")

    # Build entries, apply min_freq filter and weight scheme
    entries = []
    for key, moves in move_counts.items():
        for enc, stats in moves.items():
            freq  = stats['freq']
            score = stats['score']
            if freq < min_freq: continue

            if weight_scheme == 'freq':
                weight = min(freq, 65535)
            elif weight_scheme == 'score':
                # Scale: 0-65535 based on normalised score (0.5=neutral baseline)
                weight = max(1, int((score / freq) * 65535))
            else:  # uniform
                weight = 1

            entries.append((key, enc, weight))

    if verbose:
        print(f"  Book entries before dedup: {len(entries)}")

    # Sort by key (required by Polyglot binary format)
    entries.sort(key=lambda e: e[0])

    # Write binary
    with open(out_path, 'wb') as f:
        for key, enc, weight in entries:
            f.write(struct.pack('>QHHI', key, enc, weight, 0))

    if verbose:
        print(f"  Written {len(entries)} entries to {out_path}")
        print(f"  File size: {os.path.getsize(out_path):,} bytes")

    return len(entries), games_processed


# ─── merge ────────────────────────────────────────────────────────────────────
def merge_books(book_paths: list[str], out_path: str):
    """Merge multiple .bin books, summing weights for identical (key, move) pairs."""
    combined: dict[tuple, int] = {}
    for bp in book_paths:
        with open(bp, 'rb') as f:
            data = f.read()
        for i in range(0, len(data), 16):
            key, enc, weight, _ = struct.unpack('>QHHI', data[i:i+16])
            k = (key, enc)
            combined[k] = min(combined.get(k, 0) + weight, 65535)

    entries = sorted(combined.items(), key=lambda x: x[0][0])
    with open(out_path, 'wb') as f:
        for (key, enc), weight in entries:
            f.write(struct.pack('>QHHI', key, enc, weight, 0))
    print(f"Merged {len(book_paths)} books → {len(entries)} entries → {out_path}")


# ─── dump ─────────────────────────────────────────────────────────────────────
def decode_move(enc: int) -> str:
    ff_ = enc & 7; fr_ = (enc>>3)&7; tf_ = (enc>>6)&7; tr_ = (enc>>9)&7; pr = (enc>>12)&7
    promo_ch = {1:'n',2:'b',3:'r',4:'q'}.get(pr, '')
    return f"{chr(ord('a')+ff_)}{fr_+1}{chr(ord('a')+tf_)}{tr_+1}{promo_ch}"

def dump_book(path: str, max_entries: int = 50):
    with open(path, 'rb') as f:
        data = f.read()
    n = len(data) // 16
    print(f"{path}: {n} entries")
    print(f"{'KEY':20} {'MOVE':8} {'WEIGHT':8}")
    print("-" * 40)
    shown = 0
    for i in range(0, min(len(data), max_entries*16), 16):
        key, enc, weight, _ = struct.unpack('>QHHI', data[i:i+16])
        print(f"0x{key:016X}  {decode_move(enc):<8} {weight}")
        shown += 1
    if n > shown:
        print(f"  ... ({n - shown} more entries)")


# ─── stats ────────────────────────────────────────────────────────────────────
def book_stats(path: str):
    with open(path, 'rb') as f:
        data = f.read()
    n = len(data) // 16
    keys = collections.Counter()
    for i in range(0, len(data), 16):
        key, enc, weight, _ = struct.unpack('>QHHI', data[i:i+16])
        keys[key] += 1
    positions = len(keys)
    max_moves = max(keys.values(), default=0)
    avg_moves = sum(keys.values()) / max(positions, 1)
    print(f"File:             {path}")
    print(f"Total entries:    {n:,}")
    print(f"Unique positions: {positions:,}")
    print(f"Avg moves/pos:    {avg_moves:.2f}")
    print(f"Max moves/pos:    {max_moves}")
    print(f"File size:        {os.path.getsize(path):,} bytes")


# ─── verify ──────────────────────────────────────────────────────────────────
def verify_book(path: str):
    """Check that the book is sorted by key (required by binary search in engines)."""
    with open(path, 'rb') as f:
        data = f.read()
    n = len(data) // 16
    prev = 0
    errors = 0
    for i in range(0, len(data), 16):
        key, _, _, _ = struct.unpack('>QHHI', data[i:i+16])
        if key < prev: errors += 1
        prev = key
    if errors:
        print(f"[FAIL] {path}: {errors} ordering violations — book may not work correctly")
    else:
        print(f"[OK]   {path}: {n} entries, correctly sorted")


# ─── CLI ─────────────────────────────────────────────────────────────────────
def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest='cmd')

    # build
    p_build = sub.add_parser('build', help='Build book from PGN file(s)')
    p_build.add_argument('--pgn',       nargs='+', required=True, help='PGN file(s) or glob patterns')
    p_build.add_argument('--out',       default='book.bin',   help='Output .bin file')
    p_build.add_argument('--depth',     type=int, default=30,  help='Max half-moves per game')
    p_build.add_argument('--min-freq',  type=int, default=2,   help='Min occurrence count')
    p_build.add_argument('--result',    choices=['all','w','b','d'], default='all')
    p_build.add_argument('--weight',    choices=['freq','score','uniform'], default='freq')
    p_build.add_argument('--polyglot',  action='store_true',   help='Use standard Polyglot hash')
    p_build.add_argument('--verbose',   action='store_true')

    # merge
    p_merge = sub.add_parser('merge', help='Merge two or more .bin books')
    p_merge.add_argument('books', nargs='+')
    p_merge.add_argument('--out', required=True)

    # dump
    p_dump = sub.add_parser('dump', help='Print book entries')
    p_dump.add_argument('book')
    p_dump.add_argument('--max', type=int, default=50)

    # stats
    p_stats = sub.add_parser('stats', help='Book statistics')
    p_stats.add_argument('book')

    # verify
    p_verify = sub.add_parser('verify', help='Verify book ordering')
    p_verify.add_argument('book')

    args = ap.parse_args()
    if not args.cmd:
        ap.print_help(); return

    if args.cmd == 'build':
        pgn_files = []
        for pattern in args.pgn:
            expanded = glob.glob(pattern)
            pgn_files.extend(expanded if expanded else [pattern])
        n, g = build_book(
            pgn_files=pgn_files, out_path=args.out,
            depth=args.depth, min_freq=args.min_freq,
            result_filter=args.result, weight_scheme=args.weight,
            use_polyglot=args.polyglot, verbose=args.verbose)
        print(f"Done: {n} entries from {g} games → {args.out}")

    elif args.cmd == 'merge':
        merge_books(args.books, args.out)
    elif args.cmd == 'dump':
        dump_book(args.book, args.max)
    elif args.cmd == 'stats':
        book_stats(args.book)
    elif args.cmd == 'verify':
        verify_book(args.book)

if __name__ == '__main__':
    main()
